# Generated by Django 4.1.1 on 2022-10-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linea', '0001_initial'),
        ('vehiculo', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapersona',
            name='fkpersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
        migrations.AddField(
            model_name='internovehiculo',
            name='fkinterno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linea.interno'),
        ),
        migrations.AddField(
            model_name='internovehiculo',
            name='fkvehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo'),
        ),
        migrations.AddField(
            model_name='internopersona',
            name='fkinterno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linea.interno'),
        ),
        migrations.AddField(
            model_name='internopersona',
            name='fkpersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
        migrations.AddField(
            model_name='interno',
            name='fklinea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linea.linea'),
        ),
        migrations.AddField(
            model_name='interno',
            name='fkpersona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
        migrations.AddField(
            model_name='interno',
            name='fkvehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo'),
        ),
    ]
