# Generated by Django 4.1.1 on 2022-11-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linea', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internopersona',
            name='tipoPersona',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='lineapersona',
            name='tipoPersona',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
