# Generated by Django 4.1.1 on 2022-11-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linea', '0003_internopersona_tipopersona_lineapersona_tipopersona'),
    ]

    operations = [
        migrations.AddField(
            model_name='internopersona',
            name='fklinea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linea.linea'),
        ),
    ]
