# Generated by Django 4.1.1 on 2022-12-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linea', '0006_linea_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='fotoOficina',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
