# Generated by Django 4.1.1 on 2022-12-27 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linea', '0007_linea_fotooficina'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineavehiculo',
            name='fkinterno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linea.interno'),
        ),
        migrations.AddField(
            model_name='lineavehiculo',
            name='fkusuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
