# Generated by Django 4.1.1 on 2023-01-14 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linea', '0008_lineavehiculo_fkinterno_lineavehiculo_fkusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='fechaEliminado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='linea',
            name='fkusuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linea',
            name='fkusuarioEliminado',
            field=models.IntegerField(null=True),
        ),
    ]
