# Generated by Django 3.1.7 on 2022-09-19 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominio', '0002_delete_domicilio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('numero', models.IntegerField(null=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fkcondominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.condominio')),
            ],
        ),
    ]
