# Generated by Django 3.1.7 on 2022-09-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domicilio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
