# Generated by Django 3.1.7 on 2022-09-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domicilio', '0002_domicilio_tipo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='domicilio',
            table='administracion_domilicio',
        ),
    ]
