# Generated by Django 4.1.1 on 2022-10-16 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linea', '0001_initial'),
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='fklinea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linea.linea'),
        ),
    ]
