# Generated by Django 4.1.1 on 2022-11-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='tipoPersona',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
