# Generated by Django 4.1.1 on 2022-11-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0004_capacitacion_tipopersona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitacion',
            name='fklinea',
        ),
    ]
