# Generated by Django 4.1.1 on 2022-12-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0005_remove_capacitacion_fklinea'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='respaldo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
