# Generated by Django 4.1.1 on 2022-12-11 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linea', '0006_linea_mapa'),
        ('capacitacion', '0006_capacitacion_respaldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='fklinea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linea.linea'),
        ),
    ]
