# Generated by Django 4.1.1 on 2022-11-12 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linea', '0005_alter_internopersona_fkinterno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('emisorId', models.IntegerField()),
                ('emisor', models.CharField(max_length=200)),
                ('mensaje', models.CharField(max_length=200)),
                ('mensajeAdjunto', models.CharField(max_length=255, null=True)),
                ('fechar', models.DateTimeField()),
                ('receptorId', models.IntegerField()),
                ('receptor', models.CharField(max_length=200)),
                ('respuesta', models.CharField(max_length=200)),
                ('respuestaAdjunto', models.CharField(max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('fklinea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linea.linea')),
                ('fkusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_chat',
            },
        ),
    ]
