# Generated by Django 4.1.1 on 2022-12-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_fechar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='receptor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='receptorId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='respuesta',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
