# Generated by Django 4.1.1 on 2022-12-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_receptor_alter_chat_receptorid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='fechaEliminado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='fkusuarioEliminado',
            field=models.IntegerField(null=True),
        ),
    ]
