# Generated by Django 4.1.1 on 2022-10-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroIncidente', models.IntegerField(null=True)),
                ('fechaIncidente', models.DateTimeField()),
                ('codigoUnidad', models.CharField(max_length=25)),
                ('clasificacion', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=25)),
                ('acciones', models.CharField(max_length=25)),
                ('costo', models.IntegerField(null=True)),
                ('estados', models.CharField(max_length=25)),
                ('fechar', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'system_incidente',
            },
        ),
    ]
