# Generated by Django 4.1.1 on 2022-10-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='otro',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
