# Generated by Django 4.1.1 on 2022-11-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='otro',
        ),
    ]
