# Generated by Django 4.1.1 on 2022-10-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0004_incidente_otro'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='tipoPersona',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='otro',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
