# Generated by Django 4.1.1 on 2022-10-16 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('incidente', '0005_incidente_tipopersona_alter_incidente_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='fkpersona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
    ]
