# Generated by Django 4.1.1 on 2022-12-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0005_incidente_respaldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='fechaEliminado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='fkusuarioEliminado',
            field=models.IntegerField(null=True),
        ),
    ]
