# Generated by Django 4.1.1 on 2022-10-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0006_alter_incidente_fkpersona'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='responsable',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
