# Generated by Django 4.1.1 on 2022-10-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculoCategoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=25)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=25)),
                ('combustible', models.CharField(max_length=25, null=True)),
                ('año', models.IntegerField(null=True)),
                ('fklinea', models.IntegerField(null=True)),
                ('fkinterno', models.IntegerField(null=True)),
                ('estado', models.BooleanField(default=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('fkcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculoCategoria.vehiculocategoria')),
            ],
            options={
                'db_table': 'system_vehiculo',
            },
        ),
    ]
