# Generated by Django 4.1.1 on 2022-09-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=25)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=25)),
                ('año', models.IntegerField(null=True)),
                ('estado', models.BooleanField(default=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'system_vehiculo',
            },
        ),
    ]
