# Generated by Django 4.1.1 on 2022-12-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_vehiculo_ruat'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fotofrontal',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fotolateral',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
