# Generated by Django 4.1.1 on 2022-12-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_vehiculo_fotofrontal_vehiculo_fotolateral'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='inspeccion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='inspeccionVencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='seguro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='seguroVencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='soat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='soatVencimiento',
            field=models.DateField(null=True),
        ),
    ]
