# Generated by Django 4.1.1 on 2022-12-31 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehiculo', '0005_vehiculo_fechar_vehiculo_fkusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fklinea', models.IntegerField(null=True)),
                ('linea', models.CharField(max_length=50, null=True)),
                ('fkinterno', models.IntegerField(null=True)),
                ('interno', models.CharField(max_length=50, null=True)),
                ('nota', models.CharField(max_length=250, null=True)),
                ('fechar', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('fkusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fkvehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='vehiculo.vehiculo')),
                ('fkvehiculoTrans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo_trans', to='vehiculo.vehiculo')),
            ],
            options={
                'db_table': 'system_vehiculoTransferencia',
            },
        ),
    ]
