# Generated by Django 4.1.1 on 2023-02-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0008_vehiculo_fechaeliminado_vehiculo_fkusuarioeliminado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculotransferencia',
            old_name='fechaEliminado',
            new_name='fechaRetiro',
        ),
        migrations.RenameField(
            model_name='vehiculotransferencia',
            old_name='fkusuarioEliminado',
            new_name='fkusuarioSalida',
        ),
        migrations.AddField(
            model_name='vehiculotransferencia',
            name='fkvehiculoTransSalida',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehiculotransferencia',
            name='placa',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='vehiculotransferencia',
            name='placaTrans',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='vehiculotransferencia',
            name='placaTransSalida',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='vehiculotransferencia',
            name='usuarioSalida',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
