# Generated by Django 4.1.1 on 2022-09-28 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('licenciaNro', models.CharField(max_length=25)),
                ('licenciaCategoria', models.CharField(max_length=1)),
                ('licenciaFechaVencimiento', models.DateField()),
                ('lugarNacimiento', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'system_persona',
            },
        ),
        migrations.CreateModel(
            name='PersonaFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('FechaNacimiento', models.DateField()),
                ('lugarNacimiento', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('fkpersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
            options={
                'db_table': 'system_personaFamiliar',
            },
        ),
    ]
