# Generated by Django 4.1.1 on 2022-10-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='ciFechaVencimiento',
            new_name='FechaNacimiento',
        ),
    ]
