# Generated by Django 4.1.1 on 2022-10-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_rename_cifechavencimiento_persona_fechanacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='FechaNacimiento',
            new_name='fechaNacimiento',
        ),
    ]
