# Generated by Django 4.1.1 on 2022-10-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_rename_fechanacimiento_persona_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
