# Generated by Django 4.1.1 on 2022-10-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_persona_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fotoCi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fotoLicencia',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
