# Generated by Django 4.1.1 on 2022-12-01 23:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_persona_fotoci_persona_fotolicencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
