# Generated by Django 4.1.1 on 2022-12-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_alter_persona_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
