# Generated by Django 4.1.1 on 2022-12-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_alter_persona_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fechaInscripcion',
            field=models.DateField(null=True),
        ),
    ]
