# Generated by Django 4.1.1 on 2022-12-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_persona_certificadoinscripcion_persona_memorandum'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fechaEliminado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fkusuarioEliminado',
            field=models.IntegerField(null=True),
        ),
    ]
