# Generated by Django 4.1.1 on 2023-01-14 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persona', '0013_personatransferencia_fechar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fkusuarioCreacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fkusuarioCreacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fkusuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fkusuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
