# Generated by Django 4.1.1 on 2023-02-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0015_alter_personatransferencia_fkpersonatrans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personatransferencia',
            name='fkinterno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personatransferencia',
            name='interno',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
