# Generated by Django 4.1.1 on 2023-02-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0016_alter_personatransferencia_fkinterno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personatransferencia',
            name='fkinternoPersona',
            field=models.IntegerField(null=True),
        ),
    ]
