# Generated by Django 4.1.1 on 2023-02-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0017_personatransferencia_fkinternopersona'),
    ]

    operations = [
        migrations.AddField(
            model_name='personatransferencia',
            name='fechaRetiro',
            field=models.DateField(null=True),
        ),
    ]
