# Generated by Django 4.1.1 on 2023-02-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0018_personatransferencia_fecharetiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='personatransferencia',
            name='fkpersonaTransSalida',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personatransferencia',
            name='personaTransSalida',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
