# Generated by Django 4.1.1 on 2023-02-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0020_personatransferencia_fkusuariosalida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personatransferencia',
            name='fechaRetiro',
            field=models.DateTimeField(null=True),
        ),
    ]
