# Generated by Django 3.1.7 on 2022-09-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
