# Generated by Django 3.1.7 on 2022-09-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fechaRegistro', models.DateField(null=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True)),
                ('fkcondominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.condominio')),
            ],
        ),
    ]
