# Generated by Django 3.1.7 on 2022-09-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domicilio',
        ),
    ]
