# Generated by Django 3.1.7 on 2022-09-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_delete_domicilio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='condominio',
            table='administracion_condominio',
        ),
    ]
