# Generated by Django 3.1.7 on 2022-09-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0003_auto_20220919_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
